// Generated by 'assets_to_dart' at 2023-03-19 21:29:27.389218 -03:00

class Assets {
static const Shape = 'assets/Shape.svg';
static const salaryIcon = 'assets/salary_icon.svg';
static const WorkSans = 'assets/WorkSans.ttf';
static const localIcon = 'assets/local_icon.svg';
static const onboardingCarousel1 = 'assets/onboarding_carousel_1.svg';
static const onboardingCarousel2 = 'assets/onboarding_carousel_2.svg';
static const onboardingCarousel3 = 'assets/onboarding_carousel_3.svg';
static const anonymousUser = 'assets/anonymous_user.svg';
static const greenDownArrow = 'assets/green_down_arrow.svg';
static const logoHotaru = 'assets/logo_hotaru.png';
static const briefcase = 'assets/briefcase.svg';
static const backArrow = 'assets/back_arrow.svg';
static const womanProfile = 'assets/woman_profile.svg';
static const addFavoriteJobFull = 'assets/add_favorite_job_full.svg';
static const whatsappimage = 'assets/whatsapp.image.svg';
static const unselectedCheckbox = 'assets/unselected_checkbox.svg';
static const unselectedCircleCheckbox = 'assets/unselected_circle_checkbox.svg';
static const userimagepattern = 'assets/user.image.pattern.svg';
static const businessman = 'assets/businessman.svg';
static const genderIcon = 'assets/gender_icon.svg';
static const addProfilePicture = 'assets/add_profile_picture.svg';
static const textDeviderJobDisplay = 'assets/text_devider_job_display.svg';
static const selectedCheckbox = 'assets/selected_checkbox.svg';
static const searchFilter = 'assets/search_filter.svg';
static const close = 'assets/close.svg';
static const trash = 'assets/trash.svg';
static const placeIcon = 'assets/place_icon.svg';
static const greenRightArrow = 'assets/green_right_arrow.svg';
static const editProfilePicture = 'assets/edit_profile_picture.svg';
static const arrowLeft = 'assets/arrow-left.svg';
static const yen = 'assets/yen.svg';
static const houseOutline = 'assets/house-outline.svg';
static const eyeIsVisible = 'assets/eye_is_visible.svg';
static const selectedCircleCheckbox = 'assets/selected_circle_checkbox.svg';
static const housingIcon = 'assets/housing_icon.svg';
static const idiomLevelIcon = 'assets/idiom_level_icon.svg';
static const addJob = 'assets/add_job.svg';
static const addFavoriteJob = 'assets/add_favorite_job.svg';
static const customer = 'assets/customer.svg';
static const logoPtHotaru = 'assets/logo_pt_hotaru.svg';
}
